// demo-react/src/App.jsx
import { useEffect, useState } from "react";
import MouseTracker from "./MouseTracker";

function App() {
  const [ temperature, setTemperature ] = useState(0);
  const [ description, setDescription ] = useState("");
  const [ city, setCity ] = useState("Generic city");

  useEffect(() => {
    setTimeout(() => {
      setTemperature(27);
      setDescription("Clear");
    }, 1500);
  });

  return (
    <>
      <div class="App">
        <h1>Weather forecast at {city}</h1>
          {
            temperature
            ?
              <div>
                <p>Temperature: {temperature}°C</p>
                <p>Climate: {description}</p>
              </div>
            :
              <p>Loading...</p>
          }
      </div>

      <MouseTracker />
    </>
  );
}

export default App;

// svelte/src/App.svelte
<script>
  import { onMount } from "svelte";
  import MouseTracker from "./MouseTracker.svelte";

  let temperature;
  let description;
  let city = 'Generic city';

  onMount(() => {
    setTimeout(() => {
      temperature = 27;
      description = 'Clear';
    }, 1500)
  });
</script>

<div class="App">
  <h1>Weather forecast at {city}</h1>
  {#if temperature}
    <div>
      <p>Temperature: {temperature}°C</p>
      <p>Climate: {description}</p>
    </div>
  {:else}
    <p>Loading...</p>
  {/if}
</div>

<MouseTracker />
