// demo-react/src/MouseTracker.jsx
import { useState, useEffect } from "react";

export default function MouseTracker () {
  const [ mouseX, setMouseX ] = useState(0);
  const [ mouseY, setMouseY ] = useState(0);
  const [ numberOfClicks, setNumberOfClicks ] = useState(0);

  function handleMouseMove({ offsetX, offsetY }) {
    setMouseX(offsetX);
    setMouseY(offsetY);
  }

  function handleClick() {
    setNumberOfClicks(numberOfClicks + 1);
  }

  useEffect(() => {
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("click", handleClick);
  });

  return (
    <>
      <p>Mouse position (x/y): {mouseX}/{mouseY}</p>
      <p>Number of clicks: {numberOfClicks}</p>
    </>
  );
}

// svelte/src/MouseTracker.svelte
<script>
  let mouseY = 0;
  let mouseX = 0;
  let numberOfClicks = 0;
  
  function handleMouseMove ({ x, y }) {
    mouseX = x;
    mouseY = y;
  }

  function handleClick() {
    numberOfClicks++;
  }
</script>

<svelte:body
  on:mousemove={handleMouseMove}
  on:click={handleClick}
/>

<p>Mouse position (x/y): {mouseX}/{mouseY}</p>
<p>Number of clicks: {numberOfClicks}</p>
